language: python
python:
- 3.6
- 3.7
- 3.8
env:
- INSTALL_SKLEARN=true
- INSTALL_SKLEARN=false
before_install:
- function conda_inst { export CONDA_HOME=$HOME/conda && wget https://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh
  -O /home/travis/.cache/conda.sh && bash /home/travis/.cache/conda.sh -b -p ${CONDA_HOME}
  && export PATH=${CONDA_HOME}/bin:$PATH && hash -r && conda config --set always_yes
  yes --set changeps1 no && conda update -q conda && conda config --add channels conda-forge
  && conda install python=${TRAVIS_PYTHON_VERSION} numpy scipy nomkl pytest && if
  $INSTALL_SKLEARN; then conda install scikit-learn; fi }
- travis_retry conda_inst
install:
- travis_retry pip install -e .
script:
- py.test -v --doctest-modules mapalign
deploy:
  provider: pypi
  user: satra
  password:
    secure: YVlySO9dM4hddTsQvwsxpJH7hIj4BoyPACX/UKKaN9bBlEePV18uYXxZcoen0OgcSwFO51cR0QW3wXx0ZAONB2FSVKdt4twIqq+CE8lVFnrNtj84efD+AtA0fb7BW9Qhsc4K6wGjU18/fvRyQXom6GZSf8tfBzsGAl+jG/OWwwV6m6/fWLSCZlydyxPQMhWtwL1XXBSF3ktR/i/4DyLdd8Y3pKJo9aOobaBg5JqvwClj27sR6IBfXjnTj5AhwJsdfU8Riesvswei47V4HjlYvamEOX4xuBdvB/rqnIm5Y+V5WaLGpLyqUtt7XkIn2apdVh2078EfcK/4O6qeYKybigxLMKXL0VacmpBFMY1J87Y3EjxT43ZcKX73JkEIYoikb+LPjxKTqUHUzstpZL+/34LOs7IbcwkJg3F8H75lX2TNPNrhU8pIFIad3FtKCexm94xI4apAboQ/osG9wwnyXLKxDzJyVfepkOtT8Pfz7FFZWBPQJ3CRr/TekZvsUcKvpv5yvvxLutae+U86oi6cgYBLiAtp4ldeOMcM2QIZQ+FqhNy8ojvEcwganDJJ3xHHXEjS98t8mkPVXtgv33NU+1uvsr0bAi0/RCqLoYB81t/5ehHxKuYvgQLlD0anr5HebUi3jdU75eP4K2WGuLq+dRGyV91rlOUQEbaLhEK/M1c=
  on:
    tags: true
    repo: satra/mapalign
    branch: master
  distributions: sdist
